language: python

os:
  - linux

  # Travis-CI does not support python on OSX for some reason
  # - osx

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install .
  - pip install codecov

script:
  - python setup.py test
  - codecov
